@startuml
!pragma useCaseDiagram true
left to right direction

actor "Organisation worker" as user

rectangle "Application" {
    usecase menu as "Select option from menu"
    usecase country as "Generate country report"
    usecase city as "Generate city report"
    usecase capital as "Generate capital city report"
    usecase population as "Generate population report"
    usecase showdata as "Show data from database"
}

database "Database" as db

' Relationships
user --> menu

menu .> country : <<extend>>
menu .> city : <<extend>>
menu .> capital : <<extend>>
menu .> population : <<extend>>

country ..> showdata : <<include>>
city ..> showdata : <<include>>
capital ..> showdata : <<include>>
population ..> showdata : <<include>>

showdata <-- db

@enduml
