@startuml
'https://plantuml.com/use-case-diagram

actor user as "Organisation worker"

rectangle "Application" {
    usecase menu as "Select option from menu"
    usecase country as "Generate country report"
    usecase city as "Generate city report"
    usecase capital as "Generate capital city report"
    usecase population as "Generate population report"

    rectangle db as "Database"
}

user -- menu
menu --> country
menu --> city
menu --> capital
menu --> population

country .. db : Include
city .. db : Include
capital .. db : Include
population .. db : Include

@enduml